kind: Deployment
apiVersion: apps/v1
metadata:
  name: codedabbler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codedabbler
  template:
    metadata:
      labels:
        app: codedabbler
    spec:
      containers:
        - name: codedabbler
          image: localhost:5000/codedabbler
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

-----------------------------------------------

kind: Service
apiVersion: v1
metadata:
  name: codedabbler
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: codedabbler
