apiVersion: apps/v1
kind: Deployment
metadata:
  name: codedabbler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codedabbler
  template:
    metadata:
      labels:
        app: codedabbler
    spec:
      containers:
        - name: codedabbler
          image: localhost:5000/codedabbler
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
